/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Blood Omen: Legacy of Kain)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80077260u
#define func_80077260 BootEntry  /* alias */
